<template><h1 id="rem" tabindex="-1"><a class="header-anchor" href="#rem" aria-hidden="true">#</a> rem</h1>
<h3 id="等比例缩放" tabindex="-1"><a class="header-anchor" href="#等比例缩放" aria-hidden="true">#</a> 等比例缩放</h3>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">doc<span class="token punctuation">,</span> win</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
     <span class="token keyword">var</span> docEl <span class="token operator">=</span> doc<span class="token punctuation">.</span>documentElement<span class="token punctuation">,</span>
       resizeEvt <span class="token operator">=</span> <span class="token string">'orientationchange'</span> <span class="token keyword">in</span> window <span class="token operator">?</span> <span class="token string">'orientationchange'</span> <span class="token operator">:</span> <span class="token string">'resize'</span><span class="token punctuation">,</span>
       <span class="token function-variable function">recalc</span> <span class="token operator">=</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
         <span class="token keyword">var</span> clientWidth <span class="token operator">=</span> docEl<span class="token punctuation">.</span>clientWidth
         <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>clientWidth<span class="token punctuation">)</span> <span class="token keyword">return</span>
         docEl<span class="token punctuation">.</span>style<span class="token punctuation">.</span>fontSize <span class="token operator">=</span> <span class="token punctuation">(</span>clientWidth <span class="token operator">>=</span> <span class="token number">720</span> <span class="token operator">?</span> <span class="token number">100</span> <span class="token operator">:</span> clientWidth <span class="token operator">/</span> <span class="token number">7.5</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">'px'</span>
       <span class="token punctuation">}</span>
     <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>doc<span class="token punctuation">.</span>addEventListener<span class="token punctuation">)</span> <span class="token keyword">return</span>
     win<span class="token punctuation">.</span><span class="token function">addEventListener</span><span class="token punctuation">(</span>resizeEvt<span class="token punctuation">,</span> recalc<span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">)</span>
     doc<span class="token punctuation">.</span><span class="token function">addEventListener</span><span class="token punctuation">(</span><span class="token string">'DOMContentLoaded'</span><span class="token punctuation">,</span> recalc<span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">)</span>
   <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">(</span>document<span class="token punctuation">,</span> window<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br></div></div><h2 id="有缩放的方案" tabindex="-1"><a class="header-anchor" href="#有缩放的方案" aria-hidden="true">#</a> 有缩放的方案</h2>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>  <span class="token comment">/* 基于 ant-design-mobile 高清解决方案 */</span>
   <span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token function">calcFontSize</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
     <span class="token keyword">var</span> doc <span class="token operator">=</span> window<span class="token punctuation">.</span>document
     <span class="token keyword">var</span> docEl <span class="token operator">=</span> doc<span class="token punctuation">.</span>documentElement
     <span class="token keyword">var</span> isIOS <span class="token operator">=</span> navigator<span class="token punctuation">.</span>appVersion<span class="token punctuation">.</span><span class="token function">match</span><span class="token punctuation">(</span><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">(iphone)</span><span class="token regex-delimiter">/</span><span class="token regex-flags">gi</span></span><span class="token punctuation">)</span>
     <span class="token keyword">var</span> isAndroid <span class="token operator">=</span> navigator<span class="token punctuation">.</span>userAgent<span class="token punctuation">.</span><span class="token function">match</span><span class="token punctuation">(</span><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">Android[\S\s]+AppleWebkit\/(\d{3})</span><span class="token regex-delimiter">/</span><span class="token regex-flags">i</span></span><span class="token punctuation">)</span>
     <span class="token keyword">var</span> dpr <span class="token operator">=</span> window<span class="token punctuation">.</span>devicePixelRatio <span class="token operator">||</span> <span class="token number">1</span>
     <span class="token keyword">var</span> wWidth <span class="token operator">=</span> window<span class="token punctuation">.</span>screen<span class="token punctuation">.</span>width <span class="token operator">></span> <span class="token number">0</span> <span class="token operator">&amp;&amp;</span> <span class="token punctuation">(</span>window<span class="token punctuation">.</span>innerWidth <span class="token operator">>=</span> window<span class="token punctuation">.</span>screen<span class="token punctuation">.</span>width <span class="token operator">||</span> window<span class="token punctuation">.</span>innerWidth <span class="token operator">===</span> <span class="token number">0</span><span class="token punctuation">)</span> <span class="token operator">?</span> window<span class="token punctuation">.</span>screen<span class="token punctuation">.</span>width <span class="token operator">:</span> window<span class="token punctuation">.</span>innerWidth
     <span class="token keyword">var</span> fontScale <span class="token operator">=</span> <span class="token number">0.5</span> <span class="token comment">/* 设计稿为二倍图 */</span>
     <span class="token keyword">var</span> baseFontSize <span class="token operator">=</span> <span class="token number">100</span> <span class="token comment">/* 规定 1rem = 100px */</span>

     <span class="token doc-comment comment">/**
      * 修正rem支持问题导致计算不准
      * 如Samsung S7，fontSize设置为100px，实际1rem!=100px，
      */</span>
     <span class="token keyword">var</span> adjustScale <span class="token operator">=</span> <span class="token number">1</span>
     docEl<span class="token punctuation">.</span>style<span class="token punctuation">.</span>fontSize <span class="token operator">=</span> <span class="token string">'100px'</span>
     <span class="token keyword">var</span> tempDiv <span class="token operator">=</span> doc<span class="token punctuation">.</span><span class="token function">createElement</span><span class="token punctuation">(</span><span class="token string">'div'</span><span class="token punctuation">)</span>
     tempDiv<span class="token punctuation">.</span><span class="token function">setAttribute</span><span class="token punctuation">(</span><span class="token string">'style'</span><span class="token punctuation">,</span> <span class="token string">'width:1rem; display:none'</span><span class="token punctuation">)</span>
     docEl<span class="token punctuation">.</span><span class="token function">appendChild</span><span class="token punctuation">(</span>tempDiv<span class="token punctuation">)</span>
     <span class="token keyword">var</span> realWidth <span class="token operator">=</span> window<span class="token punctuation">.</span><span class="token function">getComputedStyle</span><span class="token punctuation">(</span>tempDiv<span class="token punctuation">)</span><span class="token punctuation">.</span>width<span class="token punctuation">;</span>
     docEl<span class="token punctuation">.</span><span class="token function">removeChild</span><span class="token punctuation">(</span>tempDiv<span class="token punctuation">)</span>
     <span class="token keyword">if</span> <span class="token punctuation">(</span>realWidth <span class="token operator">!==</span> docEl<span class="token punctuation">.</span>style<span class="token punctuation">.</span>fontSize<span class="token punctuation">)</span> <span class="token punctuation">{</span>
       adjustScale <span class="token operator">=</span> <span class="token number">100</span> <span class="token operator">/</span> <span class="token function">parseInt</span><span class="token punctuation">(</span>realWidth<span class="token punctuation">)</span>
     <span class="token punctuation">}</span>

     <span class="token doc-comment comment">/**
      * 以下情况不适用高清缩放
      *   1. 非iOS
      *   2. Android4.3及以下
      *   3. iPhone6：钱包iOS使用UIWebView，在iphone6下缩放，内容宽度会变成376，导致页面可以左右滑动
      */</span>
     <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token operator">!</span>isIOS <span class="token operator">&amp;&amp;</span> <span class="token operator">!</span><span class="token punctuation">(</span>isAndroid <span class="token operator">&amp;&amp;</span> isAndroid<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span> <span class="token operator">></span> <span class="token number">534</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token operator">||</span> <span class="token punctuation">(</span>isIOS <span class="token operator">&amp;&amp;</span> wWidth <span class="token operator">===</span> <span class="token number">375</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
       dpr <span class="token operator">=</span> <span class="token number">1</span>
     <span class="token punctuation">}</span>
     <span class="token keyword">var</span> scale <span class="token operator">=</span> <span class="token number">1</span> <span class="token operator">/</span> dpr
     docEl<span class="token punctuation">.</span><span class="token function">setAttribute</span><span class="token punctuation">(</span><span class="token string">'data-dpr'</span><span class="token punctuation">,</span> dpr<span class="token punctuation">)</span>

     <span class="token keyword">var</span> metaEl <span class="token operator">=</span> doc<span class="token punctuation">.</span><span class="token function">querySelector</span><span class="token punctuation">(</span><span class="token string">'meta[name="viewport"]'</span><span class="token punctuation">)</span>
     <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>metaEl<span class="token punctuation">)</span> <span class="token punctuation">{</span>
       metaEl <span class="token operator">=</span> doc<span class="token punctuation">.</span><span class="token function">createElement</span><span class="token punctuation">(</span><span class="token string">'meta'</span><span class="token punctuation">)</span>
       metaEl<span class="token punctuation">.</span><span class="token function">setAttribute</span><span class="token punctuation">(</span><span class="token string">'name'</span><span class="token punctuation">,</span> <span class="token string">'viewport'</span><span class="token punctuation">)</span>
       doc<span class="token punctuation">.</span>head<span class="token punctuation">.</span><span class="token function">appendChild</span><span class="token punctuation">(</span>metaEl<span class="token punctuation">)</span>
     <span class="token punctuation">}</span>
     metaEl<span class="token punctuation">.</span><span class="token function">setAttribute</span><span class="token punctuation">(</span><span class="token string">'content'</span><span class="token punctuation">,</span> <span class="token string">'width=device-width,user-scalable=no,initial-scale='</span> <span class="token operator">+</span> scale <span class="token operator">+</span> <span class="token string">',maximum-scale='</span> <span class="token operator">+</span> scale <span class="token operator">+</span> <span class="token string">',minimum-scale='</span> <span class="token operator">+</span> scale<span class="token punctuation">)</span>
     docEl<span class="token punctuation">.</span>style<span class="token punctuation">.</span>fontSize <span class="token operator">=</span> dpr <span class="token operator">*</span> fontScale <span class="token operator">*</span> baseFontSize <span class="token operator">*</span> adjustScale <span class="token operator">+</span> <span class="token string">'px'</span>

     window<span class="token punctuation">.</span><span class="token function">addEventListener</span><span class="token punctuation">(</span><span class="token string">'resize'</span><span class="token punctuation">,</span> calcFontSize<span class="token punctuation">)</span>
   <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">(</span><span class="token punctuation">)</span>

</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br><span class="line-number">38</span><br><span class="line-number">39</span><br><span class="line-number">40</span><br><span class="line-number">41</span><br><span class="line-number">42</span><br><span class="line-number">43</span><br><span class="line-number">44</span><br><span class="line-number">45</span><br><span class="line-number">46</span><br><span class="line-number">47</span><br><span class="line-number">48</span><br><span class="line-number">49</span><br><span class="line-number">50</span><br></div></div></template>
