<template><h1 id="webpack" tabindex="-1"><a class="header-anchor" href="#webpack" aria-hidden="true">#</a> webpack</h1>
<h2 id="webpack-webpack-dev-middleware-express-实现浏览器实时刷新-配置" tabindex="-1"><a class="header-anchor" href="#webpack-webpack-dev-middleware-express-实现浏览器实时刷新-配置" aria-hidden="true">#</a> webpack webpack-dev-middleware express 实现浏览器实时刷新 配置</h2>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code> <span class="token comment">//实现刷新浏览器webpack-hot-middleware/client?noInfo=true&amp;reload=true 是必填的</span>
 <span class="token literal-property property">entry</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">'webpack-hot-middleware/client?noInfo=true&amp;reload=true'</span> <span class="token punctuation">,</span> <span class="token string">'entry.js'</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><h2 id="webpack4-0-报错" tabindex="-1"><a class="header-anchor" href="#webpack4-0-报错" aria-hidden="true">#</a> webpack4.0 报错</h2>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>⠋ building <span class="token keyword">for</span> production<span class="token punctuation">..</span>.<span class="token punctuation">(</span>node:21122<span class="token punctuation">)</span> DeprecationWarning: Tapable.plugin is deprecated. Use new API on <span class="token variable"><span class="token variable">`</span>.hooks<span class="token variable">`</span></span> instead
⠸ building <span class="token keyword">for</span> production<span class="token punctuation">..</span>.<span class="token punctuation">(</span>node:21122<span class="token punctuation">)</span> <span class="token punctuation">[</span>ESLINT_LEGACY_OBJECT_REST_SPREAD<span class="token punctuation">]</span> DeprecationWarning: The <span class="token string">'parserOptions.ecmaFeatures.experimentalObjectRestSpread'</span> option is deprecated. Use <span class="token string">'parserOptions.ecmaVersion'</span> instead. <span class="token punctuation">(</span>found <span class="token keyword">in</span> <span class="token string">"standard"</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><h3 id="解决方法" tabindex="-1"><a class="header-anchor" href="#解决方法" aria-hidden="true">#</a> 解决方法</h3>
<ol>
<li>Use new API on <code>.hooks</code> instead</li>
</ol>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>⠋ building <span class="token keyword">for</span> production<span class="token punctuation">..</span>.<span class="token punctuation">(</span>node:21122<span class="token punctuation">)</span> DeprecationWarning: Tapable.plugin is deprecated. Use new API on <span class="token variable"><span class="token variable">`</span>.hooks<span class="token variable">`</span></span> instead

 是因为某个webpack 插件需要更新到 webpack4 最新api支持版本
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><ol start="2">
<li>
<p>Use 'parserOptions.ecmaVersion' instead.</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code> Use <span class="token string">'parserOptions.ecmaVersion'</span> instead.

 <span class="token comment"># 升级了 eslint-plugin-vue eslint-config-standard 解决了</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div></li>
</ol>
<h2 id="如何解决webpack-invalid-host-origin-header问题" tabindex="-1"><a class="header-anchor" href="#如何解决webpack-invalid-host-origin-header问题" aria-hidden="true">#</a> 如何解决webpack Invalid Host/Origin header问题</h2>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code> <span class="token literal-property property">devServer</span><span class="token operator">:</span> <span class="token punctuation">{</span>
   <span class="token literal-property property">clientLogLevel</span><span class="token operator">:</span> <span class="token string">'warning'</span><span class="token punctuation">,</span>
   <span class="token literal-property property">historyApiFallback</span><span class="token operator">:</span> <span class="token punctuation">{</span>
     <span class="token literal-property property">rewrites</span><span class="token operator">:</span> <span class="token punctuation">[</span>
       <span class="token punctuation">{</span> <span class="token literal-property property">from</span><span class="token operator">:</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">.*</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">,</span> <span class="token literal-property property">to</span><span class="token operator">:</span> path<span class="token punctuation">.</span>posix<span class="token punctuation">.</span><span class="token function">join</span><span class="token punctuation">(</span>config<span class="token punctuation">.</span>dev<span class="token punctuation">.</span>assetsPublicPath<span class="token punctuation">,</span> <span class="token string">'index.html'</span><span class="token punctuation">)</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
     <span class="token punctuation">]</span><span class="token punctuation">,</span>
   <span class="token punctuation">}</span><span class="token punctuation">,</span>
   <span class="token literal-property property">hot</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
   <span class="token literal-property property">disableHostCheck</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span> <span class="token comment">// 添加不检查主机</span>
   <span class="token literal-property property">contentBase</span><span class="token operator">:</span> <span class="token boolean">false</span><span class="token punctuation">,</span> <span class="token comment">// since we use CopyWebpackPlugin.</span>
   <span class="token literal-property property">compress</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
   <span class="token operator">...</span>
 <span class="token punctuation">}</span><span class="token punctuation">,</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br></div></div><h3 id="因为-webpack-本身出于安全考虑-因为不检查主机的应用程序容易受到dns重新绑定攻击。因此-在我们的开发环境下-可以禁用掉disablehostcheck这一配置项。" tabindex="-1"><a class="header-anchor" href="#因为-webpack-本身出于安全考虑-因为不检查主机的应用程序容易受到dns重新绑定攻击。因此-在我们的开发环境下-可以禁用掉disablehostcheck这一配置项。" aria-hidden="true">#</a> 因为 webpack 本身出于安全考虑，因为不检查主机的应用程序容易受到DNS重新绑定攻击。因此，在我们的开发环境下，可以禁用掉<code>disableHostCheck</code>这一配置项。</h3>
</template>
